version: '2'

services:

  # sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: idci/elasticsearch:2.4
    container_name: acme-app-elasticsearch
    build:
      context: docker/build/elasticsearch2.4
    ports:
      - "9200:9200"
      - "9300:9300"

  mysql:
    image: mysql:5.7
    container_name: acme-app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=app
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=app
    volumes:
      - /var/docker/acme/app/var/lib/mysql:/var/lib/mysql
      - ./docker/conf/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  adminer:
    image: clue/adminer
    container_name: acme-app-adminer
    environment:
      - VIRTUAL_HOST=adminer.app.acme.docker
    depends_on:
      - mysql

  php:
    image: idci/php:5.6-fpm
    container_name: acme-app-php
    build:
      context: docker/build/php5.6
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:1.10
    container_name: acme-app-nginx
    environment:
      - VIRTUAL_HOST=app.acme.docker
    volumes_from:
      - php
    volumes:
      - ./docker/conf/nginx/vhost_symfony.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

networks:

  default:
    external:
      name: dev
